name: Deploy to Server

on:
  push:
    branches:
      - main  # O el nombre de la rama que desees desplegar

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print environment variables
      run: |
        echo "SERVER_HOST=${{ secrets.SERVER_HOST }}"
        echo "SERVER_USER=${{ secrets.SERVER_USER }}"
        echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" # Consider masking this for security

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy files
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Starting deployment"
          cd /home/github/actions-runner/deploy/DeployTest
          git pull origin main
