name: Deploy static content with custom script

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using custom script
        run: |
          # Descargar el archivo HTML desde el repositorio
          git pull https://github.com/${{ github.repository }}.git

          # Ejecutar el script de implementación personalizado
          ./deploy.sh ${{ secrets.SERVER_USER }} ${{ secrets.SERVER_HOST }} index.html
