name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Imprimir clave SSH (solo para depuración)
        run: |
          echo 'Clave SSH (solo para depuración):'
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | head -n 2
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | tail -n 2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        id: test_ssh
        run: |
          echo "** Testing SSH connection... **"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo Connection successful" && echo "** SSH connection successful! **" || echo "** SSH connection failed! Check credentials and key setup. **"

      - name: Proceso de actualizacion de repositorio
        if: steps.test_ssh.outcome == 'success'
        run: |
          echo "** Verificando permisos y existencia de directorios... **"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            echo "** Directorio actual **"
            pwd
            echo "** Listar directorios y permisos **"
            ls -la /home/github/actions-runner/deploy
            echo "** Verificar permisos de los comandos **"
            which git
            which mv
            which rmdir
            echo "** ejecutar comnados **"
            cd /home/github/actions-runner/deploy/DeployTest
            git fetch origin
            git reset --hard origin/main
          EOF

