name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Imprimir clave SSH (solo para depuración)
        run: |
          echo '{{ secrets.SSH_PRIVATE_KEY }}'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection (optional)
        run: |
          echo "** Testing SSH connection... **"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo Connection successful" && echo "** SSH connection successful! **" || echo "** SSH connection failed! Check credentials and key setup. **"

      - name: Deploy files (only if SSH test succeeds)
        uses: appleboy/ssh-action@v0.1.4
        if: steps.Test_SSH_connection.outputs == 'SSH connection successful!'  # Only run if test succeeds
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/github/actions-runner/deploy
            git pull origin main

