name: Deploy static content with custom script

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using custom script
        run: |
          # No need to clone the repository, it's already available
          # deploy.sh
          scp index.html ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/github/actions-runner/deploy/index.html
